"
## Relations
======================

### Parents
| Relation | Origin | Opposite | Type | Comment |
|---|
| `abstractClassDeclarationBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptAbstractClassDeclaration` | |
| `abstractClassDeclarationDecoratorOwner` | `FASTTEntity` | `decorator` | `FASTTypeScriptAbstractClassDeclaration` | |
| `abstractClassDeclarationNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptAbstractClassDeclaration` | |
| `abstractClassDeclarationTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptAbstractClassDeclaration` | |
| `abstractMethodSignatureNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptAbstractMethodSignature` | |
| `abstractMethodSignatureParametersOwner` | `FASTTEntity` | `parameters` | `FASTTypeScriptAbstractMethodSignature` | |
| `abstractMethodSignatureReturnTypeOwner` | `FASTTEntity` | `returnType` | `FASTTypeScriptAbstractMethodSignature` | |
| `abstractMethodSignatureTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptAbstractMethodSignature` | |
| `ambientDeclarationOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptAmbientDeclaration` | |
| `argumentOwner` | `FASTTExpression` | `arguments` | `FASTTWithArguments` | my owner|
| `argumentsOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptArguments` | |
| `arrayOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptArray` | |
| `arrayPatternOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptArrayPattern` | |
| `arrowFunctionBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptArrowFunction` | |
| `arrowFunctionParameterOwner` | `FASTTEntity` | `parameter` | `FASTTypeScriptArrowFunction` | |
| `arrowFunctionParametersOwner` | `FASTTEntity` | `parameters` | `FASTTypeScriptArrowFunction` | |
| `arrowFunctionReturnTypeOwner` | `FASTTEntity` | `returnType` | `FASTTypeScriptArrowFunction` | |
| `arrowFunctionTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptArrowFunction` | |
| `asExpressionOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptAsExpression` | |
| `assignedIn` | `FASTTExpression` | `expression` | `FASTTAssignment` | Optional assignment where this expression is used|
| `assignmentExpressionLeftOwner` | `FASTTEntity` | `left` | `FASTTypeScriptAssignmentExpression` | |
| `assignmentExpressionRightOwner` | `FASTTEntity` | `right` | `FASTTypeScriptAssignmentExpression` | |
| `assignmentPatternLeftOwner` | `FASTTEntity` | `left` | `FASTTypeScriptAssignmentPattern` | |
| `assignmentPatternRightOwner` | `FASTTEntity` | `right` | `FASTTypeScriptAssignmentPattern` | |
| `augmentedAssignmentExpressionLeftOwner` | `FASTTEntity` | `left` | `FASTTypeScriptAugmentedAssignmentExpression` | |
| `augmentedAssignmentExpressionOperatorOwner` | `FASTTEntity` | `operator` | `FASTTypeScriptAugmentedAssignmentExpression` | |
| `augmentedAssignmentExpressionRightOwner` | `FASTTEntity` | `right` | `FASTTypeScriptAugmentedAssignmentExpression` | |
| `binaryExpressionLeftOwner` | `FASTTEntity` | `left` | `FASTTypeScriptBinaryExpression` | |
| `binaryExpressionOperatorOwner` | `FASTTEntity` | `operator` | `FASTTypeScriptBinaryExpression` | |
| `binaryExpressionRightOwner` | `FASTTEntity` | `right` | `FASTTypeScriptBinaryExpression` | |
| `breakStatementLabelOwner` | `FASTTEntity` | `label` | `FASTTypeScriptBreakStatement` | |
| `callExpressionArgumentsOwner` | `FASTTEntity` | `arguments` | `FASTTypeScriptCallExpression` | |
| `callExpressionFunctionOwner` | `FASTTEntity` | `function` | `FASTTypeScriptCallExpression` | |
| `callExpressionTypeArgumentsOwner` | `FASTTEntity` | `typeArguments` | `FASTTypeScriptCallExpression` | |
| `callSignatureParametersOwner` | `FASTTEntity` | `parameters` | `FASTTypeScriptCallSignature` | |
| `callSignatureReturnTypeOwner` | `FASTTEntity` | `returnType` | `FASTTypeScriptCallSignature` | |
| `callSignatureTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptCallSignature` | |
| `catchClauseBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptCatchClause` | |
| `catchClauseParameterOwner` | `FASTTEntity` | `parameter` | `FASTTypeScriptCatchClause` | |
| `catchClauseTypeOwner` | `FASTTEntity` | `type` | `FASTTypeScriptCatchClause` | |
| `classBodyDecoratorOwner` | `FASTTEntity` | `decorator` | `FASTTypeScriptClassBody` | |
| `classBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptClass` | |
| `classDeclarationBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptClassDeclaration` | |
| `classDeclarationDecoratorOwner` | `FASTTEntity` | `decorator` | `FASTTypeScriptClassDeclaration` | |
| `classDeclarationNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptClassDeclaration` | |
| `classDeclarationTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptClassDeclaration` | |
| `classDecoratorOwner` | `FASTTEntity` | `decorator` | `FASTTypeScriptClass` | |
| `classHeritageOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptClassHeritage` | |
| `classNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptClass` | |
| `classStaticBlockBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptClassStaticBlock` | |
| `classTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptClass` | |
| `conditionalTypeAlternativeOwner` | `FASTTEntity` | `alternative` | `FASTTypeScriptConditionalType` | |
| `conditionalTypeConsequenceOwner` | `FASTTEntity` | `consequence` | `FASTTypeScriptConditionalType` | |
| `conditionalTypeLeftOwner` | `FASTTEntity` | `left` | `FASTTypeScriptConditionalType` | |
| `conditionalTypeRightOwner` | `FASTTEntity` | `right` | `FASTTypeScriptConditionalType` | |
| `constructSignatureParametersOwner` | `FASTTEntity` | `parameters` | `FASTTypeScriptConstructSignature` | |
| `constructSignatureTypeOwner` | `FASTTEntity` | `type` | `FASTTypeScriptConstructSignature` | |
| `constructSignatureTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptConstructSignature` | |
| `constructorTypeParametersOwner` | `FASTTEntity` | `parameters` | `FASTTypeScriptConstructorType` | |
| `constructorTypeTypeOwner` | `FASTTEntity` | `type` | `FASTTypeScriptConstructorType` | |
| `constructorTypeTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptConstructorType` | |
| `continueStatementLabelOwner` | `FASTTEntity` | `label` | `FASTTypeScriptContinueStatement` | |
| `doStatementBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptDoStatement` | |
| `doStatementConditionOwner` | `FASTTEntity` | `condition` | `FASTTypeScriptDoStatement` | |
| `enumAssignmentNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptEnumAssignment` | |
| `enumAssignmentValueOwner` | `FASTTEntity` | `value` | `FASTTypeScriptEnumAssignment` | |
| `enumBodyNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptEnumBody` | |
| `enumDeclarationBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptEnumDeclaration` | |
| `enumDeclarationNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptEnumDeclaration` | |
| `exportClauseOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptExportClause` | |
| `exportSpecifierAliasOwner` | `FASTTEntity` | `alias` | `FASTTypeScriptExportSpecifier` | |
| `exportSpecifierNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptExportSpecifier` | |
| `exportStatementDeclarationOwner` | `FASTTEntity` | `declaration` | `FASTTypeScriptExportStatement` | |
| `exportStatementDecoratorOwner` | `FASTTEntity` | `decorator` | `FASTTypeScriptExportStatement` | |
| `exportStatementSourceOwner` | `FASTTEntity` | `source` | `FASTTypeScriptExportStatement` | |
| `exportStatementValueOwner` | `FASTTEntity` | `value` | `FASTTypeScriptExportStatement` | |
| `expressionStatementOwner` | `FASTTExpression` | `expression` | `FASTTExpressionStatement` | The expression statement that own me (if it's the case|
| `extendsClauseTypeArgumentsOwner` | `FASTTEntity` | `typeArguments` | `FASTTypeScriptExtendsClause` | |
| `extendsClauseValueOwner` | `FASTTEntity` | `value` | `FASTTypeScriptExtendsClause` | |
| `extendsTypeClauseTypeOwner` | `FASTTEntity` | `type` | `FASTTypeScriptExtendsTypeClause` | |
| `finallyClauseBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptFinallyClause` | |
| `forInStatementBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptForInStatement` | |
| `forInStatementKindOwner` | `FASTTEntity` | `kind` | `FASTTypeScriptForInStatement` | |
| `forInStatementLeftOwner` | `FASTTEntity` | `left` | `FASTTypeScriptForInStatement` | |
| `forInStatementOperatorOwner` | `FASTTEntity` | `operator` | `FASTTypeScriptForInStatement` | |
| `forInStatementRightOwner` | `FASTTEntity` | `right` | `FASTTypeScriptForInStatement` | |
| `forInStatementValueOwner` | `FASTTEntity` | `value` | `FASTTypeScriptForInStatement` | |
| `forStatementBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptForStatement` | |
| `forStatementConditionOwner` | `FASTTEntity` | `condition` | `FASTTypeScriptForStatement` | |
| `forStatementIncrementOwner` | `FASTTEntity` | `increment` | `FASTTypeScriptForStatement` | |
| `forStatementInitializerOwner` | `FASTTEntity` | `initializer` | `FASTTypeScriptForStatement` | |
| `formalParametersOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptFormalParameters` | |
| `functionDeclarationBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptFunctionDeclaration` | |
| `functionDeclarationNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptFunctionDeclaration` | |
| `functionDeclarationParametersOwner` | `FASTTEntity` | `parameters` | `FASTTypeScriptFunctionDeclaration` | |
| `functionDeclarationReturnTypeOwner` | `FASTTEntity` | `returnType` | `FASTTypeScriptFunctionDeclaration` | |
| `functionDeclarationTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptFunctionDeclaration` | |
| `functionExpressionBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptFunctionExpression` | |
| `functionExpressionNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptFunctionExpression` | |
| `functionExpressionParametersOwner` | `FASTTEntity` | `parameters` | `FASTTypeScriptFunctionExpression` | |
| `functionExpressionReturnTypeOwner` | `FASTTEntity` | `returnType` | `FASTTypeScriptFunctionExpression` | |
| `functionExpressionTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptFunctionExpression` | |
| `functionSignatureNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptFunctionSignature` | |
| `functionSignatureParametersOwner` | `FASTTEntity` | `parameters` | `FASTTypeScriptFunctionSignature` | |
| `functionSignatureReturnTypeOwner` | `FASTTEntity` | `returnType` | `FASTTypeScriptFunctionSignature` | |
| `functionSignatureTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptFunctionSignature` | |
| `functionTypeParametersOwner` | `FASTTEntity` | `parameters` | `FASTTypeScriptFunctionType` | |
| `functionTypeReturnTypeOwner` | `FASTTEntity` | `returnType` | `FASTTypeScriptFunctionType` | |
| `functionTypeTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptFunctionType` | |
| `generatorFunctionBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptGeneratorFunction` | |
| `generatorFunctionDeclarationBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptGeneratorFunctionDeclaration` | |
| `generatorFunctionDeclarationNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptGeneratorFunctionDeclaration` | |
| `generatorFunctionDeclarationParametersOwner` | `FASTTEntity` | `parameters` | `FASTTypeScriptGeneratorFunctionDeclaration` | |
| `generatorFunctionDeclarationReturnTypeOwner` | `FASTTEntity` | `returnType` | `FASTTypeScriptGeneratorFunctionDeclaration` | |
| `generatorFunctionDeclarationTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptGeneratorFunctionDeclaration` | |
| `generatorFunctionNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptGeneratorFunction` | |
| `generatorFunctionParametersOwner` | `FASTTEntity` | `parameters` | `FASTTypeScriptGeneratorFunction` | |
| `generatorFunctionReturnTypeOwner` | `FASTTEntity` | `returnType` | `FASTTypeScriptGeneratorFunction` | |
| `generatorFunctionTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptGeneratorFunction` | |
| `genericTypeNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptGenericType` | |
| `genericTypeTypeArgumentsOwner` | `FASTTEntity` | `typeArguments` | `FASTTypeScriptGenericType` | |
| `ifStatementAlternativeOwner` | `FASTTEntity` | `alternative` | `FASTTypeScriptIfStatement` | |
| `ifStatementConditionOwner` | `FASTTEntity` | `condition` | `FASTTypeScriptIfStatement` | |
| `ifStatementConsequenceOwner` | `FASTTEntity` | `consequence` | `FASTTypeScriptIfStatement` | |
| `implementsClauseOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptImplementsClause` | |
| `importAliasOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptImportAlias` | |
| `importClauseOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptImportClause` | |
| `importRequireClauseSourceOwner` | `FASTTEntity` | `source` | `FASTTypeScriptImportRequireClause` | |
| `importSpecifierAliasOwner` | `FASTTEntity` | `alias` | `FASTTypeScriptImportSpecifier` | |
| `importSpecifierNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptImportSpecifier` | |
| `importStatementSourceOwner` | `FASTTEntity` | `source` | `FASTTypeScriptImportStatement` | |
| `indexSignatureIndexTypeOwner` | `FASTTEntity` | `indexType` | `FASTTypeScriptIndexSignature` | |
| `indexSignatureNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptIndexSignature` | |
| `indexSignatureSignOwner` | `FASTTEntity` | `sign` | `FASTTypeScriptIndexSignature` | |
| `indexSignatureTypeOwner` | `FASTTEntity` | `type` | `FASTTypeScriptIndexSignature` | |
| `inferTypeOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptInferType` | |
| `instantiationExpressionFunctionOwner` | `FASTTEntity` | `function` | `FASTTypeScriptInstantiationExpression` | |
| `instantiationExpressionTypeArgumentsOwner` | `FASTTEntity` | `typeArguments` | `FASTTypeScriptInstantiationExpression` | |
| `interfaceBodyOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptInterfaceBody` | |
| `interfaceDeclarationBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptInterfaceDeclaration` | |
| `interfaceDeclarationNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptInterfaceDeclaration` | |
| `interfaceDeclarationTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptInterfaceDeclaration` | |
| `internalModuleBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptInternalModule` | |
| `internalModuleNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptInternalModule` | |
| `intersectionTypeOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptIntersectionType` | |
| `labeledStatementBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptLabeledStatement` | |
| `labeledStatementLabelOwner` | `FASTTEntity` | `label` | `FASTTypeScriptLabeledStatement` | |
| `lexicalDeclarationKindOwner` | `FASTTEntity` | `kind` | `FASTTypeScriptLexicalDeclaration` | |
| `lookupTypeOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptLookupType` | |
| `mappedTypeClauseAliasOwner` | `FASTTEntity` | `alias` | `FASTTypeScriptMappedTypeClause` | |
| `mappedTypeClauseNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptMappedTypeClause` | |
| `mappedTypeClauseTypeOwner` | `FASTTEntity` | `type` | `FASTTypeScriptMappedTypeClause` | |
| `memberExpressionObjectOwner` | `FASTTEntity` | `object` | `FASTTypeScriptMemberExpression` | |
| `memberExpressionOptionalChainOwner` | `FASTTEntity` | `optionalChain` | `FASTTypeScriptMemberExpression` | |
| `memberExpressionPropertyOwner` | `FASTTEntity` | `property` | `FASTTypeScriptMemberExpression` | |
| `methodDefinitionBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptMethodDefinition` | |
| `methodDefinitionNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptMethodDefinition` | |
| `methodDefinitionParametersOwner` | `FASTTEntity` | `parameters` | `FASTTypeScriptMethodDefinition` | |
| `methodDefinitionReturnTypeOwner` | `FASTTEntity` | `returnType` | `FASTTypeScriptMethodDefinition` | |
| `methodDefinitionTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptMethodDefinition` | |
| `methodSignatureNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptMethodSignature` | |
| `methodSignatureParametersOwner` | `FASTTEntity` | `parameters` | `FASTTypeScriptMethodSignature` | |
| `methodSignatureReturnTypeOwner` | `FASTTEntity` | `returnType` | `FASTTypeScriptMethodSignature` | |
| `methodSignatureTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptMethodSignature` | |
| `moduleBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptModule` | |
| `moduleNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptModule` | |
| `namedImportsOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptNamedImports` | |
| `nestedIdentifierObjectOwner` | `FASTTEntity` | `object` | `FASTTypeScriptNestedIdentifier` | |
| `nestedIdentifierPropertyOwner` | `FASTTEntity` | `property` | `FASTTypeScriptNestedIdentifier` | |
| `nestedTypeIdentifierModuleOwner` | `FASTTEntity` | `module` | `FASTTypeScriptNestedTypeIdentifier` | |
| `nestedTypeIdentifierNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptNestedTypeIdentifier` | |
| `newExpressionArgumentsOwner` | `FASTTEntity` | `arguments` | `FASTTypeScriptNewExpression` | |
| `newExpressionConstructorOwner` | `FASTTEntity` | `constructor` | `FASTTypeScriptNewExpression` | |
| `newExpressionTypeArgumentsOwner` | `FASTTEntity` | `typeArguments` | `FASTTypeScriptNewExpression` | |
| `objectAssignmentPatternLeftOwner` | `FASTTEntity` | `left` | `FASTTypeScriptObjectAssignmentPattern` | |
| `objectAssignmentPatternRightOwner` | `FASTTEntity` | `right` | `FASTTypeScriptObjectAssignmentPattern` | |
| `objectOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptObject` | |
| `objectPatternOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptObjectPattern` | |
| `objectTypeOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptObjectType` | |
| `optionalParameterDecoratorOwner` | `FASTTEntity` | `decorator` | `FASTTypeScriptOptionalParameter` | |
| `optionalParameterNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptOptionalParameter` | |
| `optionalParameterPatternOwner` | `FASTTEntity` | `pattern` | `FASTTypeScriptOptionalParameter` | |
| `optionalParameterTypeOwner` | `FASTTEntity` | `type` | `FASTTypeScriptOptionalParameter` | |
| `optionalParameterValueOwner` | `FASTTEntity` | `value` | `FASTTypeScriptOptionalParameter` | |
| `pairKeyOwner` | `FASTTEntity` | `key` | `FASTTypeScriptPair` | |
| `pairPatternKeyOwner` | `FASTTEntity` | `key` | `FASTTypeScriptPairPattern` | |
| `pairPatternValueOwner` | `FASTTEntity` | `value` | `FASTTypeScriptPairPattern` | |
| `pairValueOwner` | `FASTTEntity` | `value` | `FASTTypeScriptPair` | |
| `parentConditional` | `FASTTExpression` | `condition` | `FASTTWithCondition` | Optional condition statement/expression where this expression is used|
| `parentExpression` | `FASTTExpression` | `expression` | `FASTTUnaryExpression` | Parent (unary) expression|
| `parentExpressionLeft` | `FASTTExpression` | `leftOperand` | `FASTTBinaryExpression` | Parent (binary) expression of which I am left side|
| `parentExpressionRight` | `FASTTExpression` | `rightOperand` | `FASTTBinaryExpression` | Parent (binary) expression of which I am right side|
| `parenthesizedExpressionTypeOwner` | `FASTTEntity` | `type` | `FASTTypeScriptParenthesizedExpression` | |
| `programOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptProgram` | |
| `propertySignatureNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptPropertySignature` | |
| `propertySignatureTypeOwner` | `FASTTEntity` | `type` | `FASTTypeScriptPropertySignature` | |
| `publicFieldDefinitionDecoratorOwner` | `FASTTEntity` | `decorator` | `FASTTypeScriptPublicFieldDefinition` | |
| `publicFieldDefinitionNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptPublicFieldDefinition` | |
| `publicFieldDefinitionTypeOwner` | `FASTTEntity` | `type` | `FASTTypeScriptPublicFieldDefinition` | |
| `publicFieldDefinitionValueOwner` | `FASTTEntity` | `value` | `FASTTypeScriptPublicFieldDefinition` | |
| `regexFlagsOwner` | `FASTTEntity` | `flags` | `FASTTypeScriptRegex` | |
| `regexPatternOwner` | `FASTTEntity` | `pattern` | `FASTTypeScriptRegex` | |
| `requiredParameterDecoratorOwner` | `FASTTEntity` | `decorator` | `FASTTypeScriptRequiredParameter` | |
| `requiredParameterNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptRequiredParameter` | |
| `requiredParameterPatternOwner` | `FASTTEntity` | `pattern` | `FASTTypeScriptRequiredParameter` | |
| `requiredParameterTypeOwner` | `FASTTEntity` | `type` | `FASTTypeScriptRequiredParameter` | |
| `requiredParameterValueOwner` | `FASTTEntity` | `value` | `FASTTypeScriptRequiredParameter` | |
| `returnOwner` | `FASTTExpression` | `expression` | `FASTTReturnStatement` | The return statement that own the expression (if it's the case)|
| `satisfiesExpressionOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptSatisfiesExpression` | |
| `sequenceExpressionOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptSequenceExpression` | |
| `statementBlockOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptStatementBlock` | |
| `stringOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptString` | |
| `subscriptExpressionIndexOwner` | `FASTTEntity` | `index` | `FASTTypeScriptSubscriptExpression` | |
| `subscriptExpressionObjectOwner` | `FASTTEntity` | `object` | `FASTTypeScriptSubscriptExpression` | |
| `subscriptExpressionOptionalChainOwner` | `FASTTEntity` | `optionalChain` | `FASTTypeScriptSubscriptExpression` | |
| `switchBodyOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptSwitchBody` | |
| `switchCaseBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptSwitchCase` | |
| `switchCaseValueOwner` | `FASTTEntity` | `value` | `FASTTypeScriptSwitchCase` | |
| `switchDefaultBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptSwitchDefault` | |
| `switchStatementBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptSwitchStatement` | |
| `switchStatementValueOwner` | `FASTTEntity` | `value` | `FASTTypeScriptSwitchStatement` | |
| `templateLiteralTypeOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptTemplateLiteralType` | |
| `templateStringOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptTemplateString` | |
| `ternaryExpressionAlternativeOwner` | `FASTTEntity` | `alternative` | `FASTTypeScriptTernaryExpression` | |
| `ternaryExpressionConditionOwner` | `FASTTEntity` | `condition` | `FASTTypeScriptTernaryExpression` | |
| `ternaryExpressionConsequenceOwner` | `FASTTEntity` | `consequence` | `FASTTypeScriptTernaryExpression` | |
| `tryStatementBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptTryStatement` | |
| `tryStatementFinalizerOwner` | `FASTTEntity` | `finalizer` | `FASTTypeScriptTryStatement` | |
| `tryStatementHandlerOwner` | `FASTTEntity` | `handler` | `FASTTypeScriptTryStatement` | |
| `tupleTypeOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptTupleType` | |
| `typeAliasDeclarationNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptTypeAliasDeclaration` | |
| `typeAliasDeclarationTypeParametersOwner` | `FASTTEntity` | `typeParameters` | `FASTTypeScriptTypeAliasDeclaration` | |
| `typeAliasDeclarationValueOwner` | `FASTTEntity` | `value` | `FASTTypeScriptTypeAliasDeclaration` | |
| `typeArgumentsOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptTypeArguments` | |
| `typeAssertionOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptTypeAssertion` | |
| `typeParameterConstraintOwner` | `FASTTEntity` | `constraint` | `FASTTypeScriptTypeParameter` | |
| `typeParameterNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptTypeParameter` | |
| `typeParameterValueOwner` | `FASTTEntity` | `value` | `FASTTypeScriptTypeParameter` | |
| `typeParametersOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptTypeParameters` | |
| `typePredicateNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptTypePredicate` | |
| `typePredicateTypeOwner` | `FASTTEntity` | `type` | `FASTTypeScriptTypePredicate` | |
| `unaryExpressionArgumentOwner` | `FASTTEntity` | `argument` | `FASTTypeScriptUnaryExpression` | |
| `unaryExpressionOperatorOwner` | `FASTTEntity` | `operator` | `FASTTypeScriptUnaryExpression` | |
| `unionTypeOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptUnionType` | |
| `updateExpressionArgumentOwner` | `FASTTEntity` | `argument` | `FASTTypeScriptUpdateExpression` | |
| `updateExpressionOperatorOwner` | `FASTTEntity` | `operator` | `FASTTypeScriptUpdateExpression` | |
| `variableDeclarationOwner` | `FASTTEntity` | `childrenNodes` | `FASTTypeScriptVariableDeclaration` | |
| `variableDeclaratorNameOwner` | `FASTTEntity` | `name` | `FASTTypeScriptVariableDeclarator` | |
| `variableDeclaratorTypeOwner` | `FASTTEntity` | `type` | `FASTTypeScriptVariableDeclarator` | |
| `variableDeclaratorValueOwner` | `FASTTEntity` | `value` | `FASTTypeScriptVariableDeclarator` | |
| `whileStatementBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptWhileStatement` | |
| `whileStatementConditionOwner` | `FASTTEntity` | `condition` | `FASTTypeScriptWhileStatement` | |
| `withStatementBodyOwner` | `FASTTEntity` | `body` | `FASTTypeScriptWithStatement` | |
| `withStatementObjectOwner` | `FASTTEntity` | `object` | `FASTTypeScriptWithStatement` | |

### Children
| Relation | Origin | Opposite | Type | Comment |
|---|
| `left` | `FASTTypeScriptObjectAssignmentPattern` | `objectAssignmentPatternLeftOwner` | `FASTTEntity` | |
| `right` | `FASTTypeScriptObjectAssignmentPattern` | `objectAssignmentPatternRightOwner` | `FASTTEntity` | |


## Properties
======================

| Name | Type | Default value | Comment |
|---|
| `endPos` | `Number` | nil | |
| `startPos` | `Number` | nil | |

"
Class {
	#name : 'FASTTypeScriptObjectAssignmentPattern',
	#superclass : 'FASTTypeScriptEntity',
	#traits : 'FASTTExpression',
	#classTraits : 'FASTTExpression classTrait',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptObjectAssignmentPattern class >> annotation [

	<FMClass: #ObjectAssignmentPattern super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]

{ #category : 'accessing' }
FASTTypeScriptObjectAssignmentPattern >> left [
	"Relation named: #left type: #FASTTEntity opposite: #objectAssignmentPatternLeftOwner"

	<generated>
	<FMProperty: #left type: #FASTTEntity opposite: #objectAssignmentPatternLeftOwner>
	^ self attributeAt: #left ifAbsent: [ nil ]
]

{ #category : 'accessing' }
FASTTypeScriptObjectAssignmentPattern >> left: anObject [

	<generated>
	(self attributeAt: #left ifAbsentPut: [nil]) == anObject ifTrue: [ ^ anObject ].
	anObject ifNil: [ | otherSide |
		otherSide :=  self left.
		self attributeAt: #left put: anObject.
		otherSide objectAssignmentPatternLeftOwner: nil ]
	ifNotNil: [ 
		self attributeAt: #left put: anObject.
		anObject objectAssignmentPatternLeftOwner: self ]
]

{ #category : 'navigation' }
FASTTypeScriptObjectAssignmentPattern >> leftGroup [
	<generated>
	<navigation: 'Left'>
	^ MooseSpecializedGroup with: self left
]

{ #category : 'accessing' }
FASTTypeScriptObjectAssignmentPattern >> right [
	"Relation named: #right type: #FASTTEntity opposite: #objectAssignmentPatternRightOwner"

	<generated>
	<FMProperty: #right type: #FASTTEntity opposite: #objectAssignmentPatternRightOwner>
	^ self attributeAt: #right ifAbsent: [ nil ]
]

{ #category : 'accessing' }
FASTTypeScriptObjectAssignmentPattern >> right: anObject [

	<generated>
	(self attributeAt: #right ifAbsentPut: [nil]) == anObject ifTrue: [ ^ anObject ].
	anObject ifNil: [ | otherSide |
		otherSide :=  self right.
		self attributeAt: #right put: anObject.
		otherSide objectAssignmentPatternRightOwner: nil ]
	ifNotNil: [ 
		self attributeAt: #right put: anObject.
		anObject objectAssignmentPatternRightOwner: self ]
]

{ #category : 'navigation' }
FASTTypeScriptObjectAssignmentPattern >> rightGroup [
	<generated>
	<navigation: 'Right'>
	^ MooseSpecializedGroup with: self right
]
