Class {
	#name : 'FASTTypeScriptAssertsAnnotation',
	#superclass : 'FASTTypeScriptEntity',
	#traits : 'FASTTypeScriptTReturnType',
	#classTraits : 'FASTTypeScriptTReturnType classTrait',
	#category : 'FAST-TypeScript-Model-Entities',
	#package : 'FAST-TypeScript-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTTypeScriptAssertsAnnotation class >> annotation [

	<FMClass: #AssertsAnnotation super: #FASTTypeScriptEntity>
	<package: #'FAST-TypeScript-Model'>
	<generated>
	^ self
]
